export const TILE_SIZE = 8;

export const TILE_COLORS = {
  '1':'#43567e','2':'#744646','3':'#8b76c4','4':'#c57047',
  '5':'#999675','6':'#548c66','7':'#5a5f6c','8':'#4d7a81',
  '9':'#8a6a48','a':'#d1b450','b':'#686880','c':'#db80ab',
  'd':'#f5c274','e':'#83dbcd','f':'#b6b6c2',
};

export const ROOM_COLORS = [
  '#4a5a7a','#7a4a4a','#7a6a4a','#4a7a4a',
  '#4a6a7a','#6a4a7a','#7a4a6a','#6a7a4a',
];

export const ENTITY_COLOR = {
  player:'#00ff88',strawberry:'#ff4040',goldenBerry:'#ffd700',
  spring:'#00ffcc',booster:'#ff8800',refill:'#00aaff',checkpoint:'#ffff44',
  jumpThru:'#cc9955',spikesUp:'#ff5555',spikesDown:'#ff5555',
  spikesLeft:'#ff5555',spikesRight:'#ff5555',zipMover:'#8888ff',
  fallingBlock:'#cc7744',crumbleBlock:'#aa6644',moveBlock:'#4488cc',
  killbox:'#cc2222',tentacles:'#aa44cc',colorSwitch:'#44ccaa',
  bonfire:'#ff6622',flutterbird:'#88ccff',npc:'#ffcc88',
  friendlyGhost:'#ccaaff',oshiro:'#ff88aa',
  badelineBoost:'#8844cc',badeline:'#cc4488',seeker:'#cc4444',
  dreamBlock:'#224466',switchGate:'#44cc88',
  cassette:'#ff66aa',cassetteBlock:'#ff66aa',
  dreamBerry:'#6644cc',linkedZipMover:'#6688ff',
  customSpinner:'#aaeeff',customBooster:'#ffcc44',
  decal:'#888844',trigger:'#ff8800',
};

export const TILE_PALETTE = ['1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'];

export const ENTITY_TYPES = [
  { name:'player',           w:8,  h:11, cat:'Spawn' },
  { name:'checkpoint',       w:36, h:36, cat:'Spawn' },
  { name:'strawberry',       w:14, h:14, cat:'Collectible' },
  { name:'goldenBerry',      w:14, h:14, cat:'Collectible' },
  { name:'cassette',         w:16, h:16, cat:'Collectible' },
  { name:'heartGem',         w:16, h:16, cat:'Collectible' },
  { name:'key',              w:12, h:12, cat:'Collectible' },
  { name:'berryFlying',      w:14, h:14, cat:'Collectible' },
  { name:'spring',           w:8,  h:6,  cat:'Aid' },
  { name:'booster',          w:18, h:18, cat:'Aid' },
  { name:'greenBooster',     w:18, h:18, cat:'Aid' },
  { name:'refill',           w:16, h:16, cat:'Aid' },
  { name:'twoDashRefill',    w:16, h:16, cat:'Aid' },
  { name:'feather',          w:16, h:16, cat:'Aid' },
  { name:'dreamBlock',       w:64, h:24, cat:'Aid', resizable:true },
  { name:'switchGate',       w:32, h:32, cat:'Aid', resizable:true },
  { name:'bumper',           w:24, h:24, cat:'Aid' },
  { name:'badelineBoost',    w:16, h:16, cat:'Aid' },
  { name:'puffer',           w:12, h:12, cat:'Aid' },
  { name:'jumpThru',         w:64, h:5,  cat:'Platform', resizable:true },
  { name:'fallingBlock',     w:48, h:8,  cat:'Platform', resizable:true },
  { name:'crumbleBlock',     w:16, h:8,  cat:'Platform', resizable:true },
  { name:'moveBlock',        w:24, h:24, cat:'Platform', resizable:true },
  { name:'zipMover',         w:16, h:16, cat:'Platform' },
  { name:'floatySpaceBlock', w:16, h:16, cat:'Platform', resizable:true },
  { name:'risingLava',       w:16, h:16, cat:'Platform' },
  { name:'sandwichLava',     w:16, h:16, cat:'Platform' },
  { name:'movingPlatform',   w:64, h:8,  cat:'Platform' },
  { name:'sinkingPlatform',  w:64, h:8,  cat:'Platform' },
  { name:'trapdoor',         w:32, h:16, cat:'Platform', resizable:true },
  { name:'spikesUp',         w:8,  h:4,  cat:'Hazard', resizable:true },
  { name:'spikesDown',       w:8,  h:4,  cat:'Hazard', resizable:true },
  { name:'spikesLeft',       w:4,  h:8,  cat:'Hazard', resizable:true },
  { name:'spikesRight',      w:4,  h:8,  cat:'Hazard', resizable:true },
  { name:'killbox',          w:64, h:16, cat:'Hazard', resizable:true },
  { name:'tentacles',        w:12, h:24, cat:'Hazard' },
  { name:'seeker',           w:12, h:12, cat:'Hazard' },
  { name:'eyebat',           w:16, h:16, cat:'Hazard' },
  { name:'bat',              w:8,  h:8,  cat:'Hazard' },
  { name:'fireBarrier',      w:16, h:16, cat:'Hazard', resizable:true },
  { name:'npc',              w:8,  h:16, cat:'NPC' },
  { name:'friendlyGhost',    w:16, h:16, cat:'NPC' },
  { name:'oshiro',           w:16, h:24, cat:'NPC' },
  { name:'badeline',         w:8,  h:16, cat:'NPC' },
  { name:'theo',             w:8,  h:16, cat:'NPC' },
  { name:'bird',             w:16, h:16, cat:'NPC' },
  { name:'flutterbird',      w:16, h:16, cat:'NPC' },
  { name:'granny',           w:16, h:16, cat:'NPC' },
  { name:'bonfire',          w:16, h:16, cat:'Env' },
  { name:'waterfall',        w:8,  h:32, cat:'Env', resizable:true },
  { name:'water',            w:32, h:32, cat:'Env', resizable:true },
  { name:'cassetteBlock',    w:32, h:16, cat:'Env', resizable:true },
  { name:'colorSwitch',      w:16, h:16, cat:'Env' },
  { name:'bigWaterfall',     w:8,  h:64, cat:'Env', resizable:true },
  { name:'glassBlock',       w:32, h:32, cat:'Env', resizable:true },
  { name:'darkChaser',       w:8,  h:16, cat:'Env' },
  { name:'dreamBerry',       w:14, h:14, cat:'CommunalHelper' },
  { name:'linkedZipMover',   w:16, h:16, cat:'CommunalHelper' },
  { name:'customSpinner',    w:16, h:16, cat:'FrostHelper' },
  { name:'customBooster',    w:18, h:18, cat:'FrostHelper' },
  { name:'coloredBumper',    w:24, h:24, cat:'MaxHelpingHand' },
  { name:'flagTogglePedestal',w:16,h:24, cat:'MaxHelpingHand' },
];

export const TRIGGER_TYPES = [
  { name:'musicTrigger',              w:64, h:24, cat:'Audio' },
  { name:'musicFadeTrigger',          w:64, h:24, cat:'Audio' },
  { name:'ambienceParamTrigger',      w:64, h:24, cat:'Audio' },
  { name:'soundAreaTrigger',          w:64, h:24, cat:'Audio' },
  { name:'altMusicTrigger',           w:64, h:24, cat:'Audio' },
  { name:'cameraOffsetTrigger',       w:64, h:24, cat:'Camera' },
  { name:'cameraTargetTrigger',       w:64, h:24, cat:'Camera' },
  { name:'smoothCameraOffsetTrigger', w:64, h:24, cat:'Camera' },
  { name:'noRefillTrigger',           w:64, h:24, cat:'Gameplay' },
  { name:'windTrigger',               w:64, h:24, cat:'Gameplay' },
  { name:'windAttackTrigger',         w:64, h:24, cat:'Gameplay' },
  { name:'changeRespawnTrigger',      w:64, h:24, cat:'Gameplay' },
  { name:'oshiroTrigger',             w:64, h:24, cat:'Gameplay' },
  { name:'lightFadeTrigger',          w:64, h:24, cat:'Visual' },
  { name:'bloomFadeTrigger',          w:64, h:24, cat:'Visual' },
  { name:'colorGradeTrigger',         w:64, h:24, cat:'Visual' },
  { name:'blackholeStrength',         w:64, h:24, cat:'Visual' },
  { name:'roomNameTrigger',           w:64, h:24, cat:'Meta' },
  { name:'spawnFacingTrigger',        w:64, h:24, cat:'Meta' },
  { name:'minitextboxTrigger',        w:64, h:24, cat:'Meta' },
  { name:'eventTrigger',              w:64, h:24, cat:'Meta' },
  { name:'goldenBerryCollect',        w:64, h:24, cat:'Meta' },
  { name:'luaCutsceneTrigger',        w:64, h:24, cat:'Meta' },
  { name:'stopBoostTrigger',          w:64, h:24, cat:'Meta' },
  { name:'gravityTrigger',            w:64, h:24, cat:'Helper' },
  { name:'flagTrigger',               w:64, h:24, cat:'Helper' },
  { name:'stylegroundTrigger',        w:64, h:24, cat:'Helper' },
];

export const MOD_BROWSER = [
  { name:'Loenn (Map Editor)', desc:'Official visual Celeste map editor, full entity/trigger/plugin system.', url:'https://github.com/CelestialCartographers/Loenn', tag:'tool' },
  { name:'Ahorn (legacy)',     desc:'Predecessor to Loenn built on Maple. Useful for older mods.',           url:'https://github.com/CelestialCartographers/Ahorn', tag:'tool' },
  { name:'Everest',            desc:'Core mod loader/framework for Celeste. Required for all mods.',         url:'https://github.com/EverestAPI/Everest', tag:'framework' },
  { name:'Desolo Zantas',      desc:'20+ chapter Kirby-inspired campaign mod (MaggyHelper, D-sides, DX).',   url:'https://github.com/Magedeline/Celeste__Desolo_Zantas', tag:'campaign' },
  { name:'CommunalHelper',     desc:'Dream switches, rope blocks, community-built entity collection.',       url:'https://github.com/CommunalHelper/CommunalHelper', tag:'helper' },
  { name:'FrostHelper',        desc:'Custom spinners/boosters/springs, session flag utilities.',             url:'https://github.com/JaThePlayer/FrostHelper', tag:'helper' },
  { name:'MaxHelpingHand',     desc:'Colored bumpers, flag-gated objects, multi-node platforms.',            url:'https://github.com/max4805/MaxHelpingHand', tag:'helper' },
  { name:'VivHelper',          desc:'Custom actors, dash mechanics, death effects, movement helpers.',       url:'https://github.com/Viv-0/VivHelper', tag:'helper' },
  { name:'DJMapHelper',        desc:'Visual effects, custom music helpers, additional entities.',            url:'https://github.com/DJYoshi/DJMapHelper', tag:'helper' },
  { name:'SkinModHelper',      desc:'Character skin replacement framework used by Desolo Zantas.',          url:'https://github.com/AAA1459/SkinModHelper', tag:'helper' },
  { name:'AdventureHelper',    desc:'Dash panels, timed switches, inventory system, adventure mechanics.',   url:'https://github.com/StrawberryJam2021/AdventureHelper', tag:'helper' },
  { name:'Spring Collab 2020', desc:'Community jam collab with 100+ rooms and many helper integrations.',   url:'https://github.com/EverestAPI/SpringCollab2020', tag:'campaign' },
  { name:'Maple (map library)',desc:'Programmatic Celeste map generator / Ahorn data model layer.',         url:'https://github.com/CelestialCartographers/Maple', tag:'tool' },
  { name:'Mod Structure Wiki', desc:'Everest mod file layout, binary map format, mod structure guide.',     url:'https://github.com/EverestAPI/Resources/wiki/Mod-Structure', tag:'docs' },
];

export const HANDLES = ['nw','n','ne','e','se','s','sw','w'];
export const HANDLE_SIZE = 7;
export const HANDLE_CURSOR = {
  nw:'nw-resize', n:'n-resize',  ne:'ne-resize', e:'e-resize',
  se:'se-resize', s:'s-resize',  sw:'sw-resize', w:'w-resize',
};
